// alerts
export const CREATE_ALERT = 'podbaby/CREATE_ALERT';
export const DISMISS_ALERT = 'podbaby/DISMISS_ALERT';

// auth
export const FETCH_USER_FAILURE = 'podbaby/FETCH_USER_FAILURE';
export const FETCH_USER_REQUEST = 'podbaby/FETCH_USER_REQUEST';
export const FETCH_USER_SUCCESS = 'podbaby/FETCH_USER_SUCCESS';
export const CHANGE_EMAIL = 'podbaby/CHANGE_EMAIL';
export const LOGOUT = 'podbaby/LOGOUT';
export const NOT_AUTHENTICATED = 'podbaby/NOT_AUTHENTICATED';

// bookmarks
export const ADD_BOOKMARK = 'podbaby/ADD_BOOKMARK';
export const REMOVE_BOOKMARK = 'podbaby/REMOVE_BOOKMARK';

// categories
export const FETCH_CATEGORIES_FAILURE = 'podbaby/FETCH_CATEGORIES_FAILURE';
export const FETCH_CATEGORIES_REQUEST = 'podbaby/FETCH_CATEGORIES_REQUEST';
export const FETCH_CATEGORIES_SUCCESS = 'podbaby/FETCH_CATEGORIES_SUCCESS';

// category
export const FETCH_CATEGORY_REQUEST = 'podbaby/FETCH_CATEGORY_REQUEST';
export const FETCH_CATEGORY_SUCCESS = 'podbaby/FETCH_CATEGORY_SUCCESS';
export const FETCH_CATEGORY_FAILURE = 'podbaby/FETCH_CATEGORY_FAILURE';

export const FETCH_CATEGORY_CHANNELS_FAILURE = 'podbaby/FETCH_CATEGORY_CHANNELS_FAILURE';
export const FETCH_CATEGORY_CHANNELS_REQUEST = 'podbaby/FETCH_CATEGORY_CHANNELS_REQUEST';
export const FETCH_CATEGORY_CHANNELS_SUCCESS = 'podbaby/FETCH_CATEGORY_CHANNELS_SUCCESS';


// channels
export const FETCH_CHANNELS_FAILURE = 'podbaby/FETCH_CHANNELS_FAILURE';
export const FETCH_CHANNELS_REQUEST = 'podbaby/FETCH_CHANNELS_REQUEST';
export const FETCH_CHANNELS_SUCCESS = 'podbaby/FETCH_CHANNELS_SUCCESS';

export const FETCH_ALL_CHANNELS_REQUEST = 'podbaby/FETCH_ALL_CHANNELS_REQUEST';
export const FETCH_SUBSCRIBED_CHANNELS_REQUEST = 'podbaby/FETCH_SUBSCRIBED_CHANNELS_REQUEST';

// channel
export const FETCH_CHANNEL_FAILURE = 'podbaby/FETCH_CHANNEL_FAILURE';
export const FETCH_CHANNEL_REQUEST = 'podbaby/FETCH_CHANNEL_REQUEST';
export const FETCH_CHANNEL_SUCCESS = 'podbaby/FETCH_CHANNEL_SUCCESS';

export const FETCH_CHANNEL_EPISODES_REQUEST = 'podbaby/FETCH_CHANNEL_EPISODES_REQUEST';

// episodes
export const FETCH_EPISODES_FAILURE = 'podbaby/FETCH_EPISODES_FAILURE';
export const FETCH_EPISODES_SUCCESS = 'podbaby/FETCH_EPISODES_SUCCESS';
export const FETCH_EPISODES_REQUEST = 'podbaby/FETCH_EPISODES_REQUEST';

export const FETCH_ALL_EPISODES_REQUEST = 'podbaby/FETCH_ALL_EPISODES_REQUEST';

export const FETCH_SUBSCRIBED_EPISODES_REQUEST = 'podbaby/FETCH_SUBSCRIBED_EPISODES_REQUEST';

export const FETCH_BOOKMARKED_EPISODES_REQUEST = 'podbaby/FETCH_BOOKMARKED_EPISODES_REQUEST';

export const FETCH_PLAYED_EPISODES_REQUEST = 'podbaby/FETCH_PLAYED_EPISODES_REQUEST';

// episode
export const FETCH_EPISODE_FAILURE = 'podbaby/FETCH_EPISODE_FAILURE';
export const FETCH_EPISODE_REQUEST = 'podbaby/FETCH_EPISODE_REQUEST';
export const FETCH_EPISODE_SUCCESS = 'podbaby/FETCH_EPISODE_SUCCESS';

// player
export const RELOAD_PLAYER = 'podbaby/RELOAD_PLAYER';
export const START_PLAYER = 'podbaby/START_PLAYER';
export const STOP_PLAYER = 'podbaby/STOP_PLAYER';
export const UPDATE_PLAYER_TIME = 'podbaby/UPDATE_PLAYER_TIME';

// history
export const CLEAR_HISTORY = 'podbaby/CLEAR_HISTORY';

// subscriptions
export const SUBSCRIBE = 'podbaby/SUBSCRIBE';
export const UNSUBSCRIBE = 'podbaby/UNSUBSCRIBE';
