# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-27 12:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=200)),
                ('rss_feed', models.URLField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('explicit', models.BooleanField(default=False)),
                ('copyright', models.CharField(blank=True, max_length=100)),
                ('creative_commons', models.CharField(blank=True, max_length=60)),
                ('image', models.ImageField(upload_to='images')),
                ('categories', models.ManyToManyField(blank=True, to='podcasts.Category')),
                ('finder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
            },
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('title', models.CharField(max_length=200)),
                ('explicit', models.BooleanField(default=False)),
                ('subtitle', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('summary', models.TextField(blank=True)),
                ('author', models.CharField(blank=True, max_length=100)),
                ('creative_commons', models.CharField(blank=True, max_length=60)),
                ('published', models.DateTimeField(blank=True, null=True)),
                ('duration', models.CharField(blank=True, max_length=10)),
                ('enclosure_url', models.URLField(blank=True, null=True)),
                ('enclosure_length', models.BigIntegerField(blank=True, null=True)),
                ('enclosure_type', models.CharField(blank=True, max_length=20)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='podcasts.Channel')),
            ],
            options={
                'abstract': False,
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
            },
        ),
    ]
