# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-27 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0002_auto_20160827_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='episode',
            name='link',
            field=models.URLField(blank=True),
        ),
    ]
