# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-27 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0004_auto_20160827_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='published',
            field=models.DateField(blank=True, null=True),
        ),
    ]
