# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-17 14:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('channels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('guid', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('link', models.URLField(blank=True)),
                ('explicit', models.BooleanField(default=False)),
                ('subtitle', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('summary', models.TextField(blank=True)),
                ('author', models.CharField(blank=True, max_length=100)),
                ('creative_commons', models.CharField(blank=True, max_length=60)),
                ('published', models.DateField(blank=True, null=True)),
                ('duration', models.CharField(blank=True, max_length=10)),
                ('enclosure_url', models.URLField(blank=True, null=True)),
                ('enclosure_length', models.BigIntegerField(blank=True, null=True)),
                ('enclosure_type', models.CharField(blank=True, max_length=20)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='channels.Channel')),
            ],
            options={
                'ordering': ('-published', '-created'),
            },
        ),
        migrations.AlterUniqueTogether(
            name='episode',
            unique_together=set([('channel', 'guid')]),
        ),
    ]
