# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-18 13:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookmarks', '0001_initial'),
        ('episodes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='episodes', through='bookmarks.Bookmark', to=settings.AUTH_USER_MODEL),
        ),
    ]
