# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-01 18:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('episodes', '0002_episode_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='users',
        ),
        migrations.AddField(
            model_name='episode',
            name='bookmarkers',
            field=models.ManyToManyField(blank=True, related_name='bookmarks', through='bookmarks.Bookmark', to=settings.AUTH_USER_MODEL),
        ),
    ]
