# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-13 21:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('history', '0001_initial'),
        ('episodes', '0003_auto_20161001_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='players',
            field=models.ManyToManyField(blank=True, related_name='played', through='history.Play', to=settings.AUTH_USER_MODEL),
        ),
    ]
