# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-26 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('episodes', '0005_auto_20161126_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='enclosure_url',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='link',
            field=models.URLField(blank=True, max_length=250),
        ),
    ]
