# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-26 15:17
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('episodes', '0006_auto_20161126_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='creative_commons',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='enclosure_url',
            field=models.TextField(blank=True, default='', validators=[django.core.validators.URLValidator()]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='episode',
            name='link',
            field=models.TextField(blank=True, validators=[django.core.validators.URLValidator()]),
        ),
    ]
