# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-26 18:37
from __future__ import unicode_literals

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('episodes', '0008_auto_20161126_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
    ]
