# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-26 18:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('episodes', '0009_episode_search_vector'),
    ]

    operations = [
        migrations.RunSQL("""
CREATE TRIGGER tsvectorupdate BEFORE INSERT OR UPDATE
ON episodes_episode FOR EACH ROW EXECUTE PROCEDURE
tsvector_update_trigger(
search_vector, 'pg_catalog.english', title, description);
        """,
        "DROP TRIGGER tsvectorupdate ON episodes_epsiode;"
        ),
    ]
