# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-17 14:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('rss_feed', models.URLField(unique=True)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('link', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('explicit', models.BooleanField(default=False)),
                ('copyright', models.CharField(blank=True, max_length=100)),
                ('creative_commons', models.CharField(blank=True, max_length=60)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('categories', models.ManyToManyField(blank=True, to='categories.Category')),
                ('finder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name', '-created'),
            },
        ),
    ]
