# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-01 18:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('channels', '0002_remove_channel_finder'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='subscribers',
            field=models.ManyToManyField(blank=True, related_name='subcriptions', through='subscriptions.Subscription', to=settings.AUTH_USER_MODEL),
        ),
    ]
