# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-26 14:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0003_channel_subscribers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='subscribers',
            field=models.ManyToManyField(blank=True, related_name='subscriptions', through='subscriptions.Subscription', to=settings.AUTH_USER_MODEL),
        ),
    ]
