# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-26 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0004_auto_20161126_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='link',
            field=models.URLField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='channel',
            name='rss_feed',
            field=models.URLField(max_length=250, unique=True),
        ),
    ]
