# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-26 15:17
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0005_auto_20161126_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='copyright',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='channel',
            name='creative_commons',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='channel',
            name='link',
            field=models.TextField(blank=True, validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AlterField(
            model_name='channel',
            name='rss_feed',
            field=models.TextField(unique=True, validators=[django.core.validators.URLValidator()]),
        ),
    ]
