# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-26 19:25
from __future__ import unicode_literals

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0006_auto_20161126_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
    ]
